CREATE DATABASE autosell;

use autosell;

CREATE TABLE USER (
    UNUM INT NOT NULL,
    ULOGIN NVARCHAR(32) UNIQUE NOT NULL,
    UPHONE VARCHAR(16) UNIQUE NOT NULL
    UEMAIL NVARCHAR(64) UNIQUE NOT NULL,
    UPASS VARCHAR(32) NOT NULL,
    UTYPE ENUM('User','Admin') NOT NULL
);

CREATE TABLE BRAND (
	BNUM INT NOT NULL;
	BNAME NVARCHAR(32) UNIQUE NOT NULL
);



