CREATE DATABASE autosell;

use autosell;

CREATE TABLE USERS (
    UNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ULOGIN NVARCHAR(32) UNIQUE NOT NULL,
    UPHONE VARCHAR(16) UNIQUE NOT NULL,	
    UEMAIL NVARCHAR(64) UNIQUE NOT NULL,
    UPASS VARCHAR(32) NOT NULL,
    UTYPE ENUM('User','Admin') NOT NULL
);

CREATE TABLE BRAND (
	BNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BNAME NVARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE MODEL (
	MNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BNUM INT NOT NULL,
	MNAME NVARCHAR(32) UNIQUE NOT NULL,

	FOREIGN KEY (BNUM) REFERENCES BRAND(BNUM)
);

CREATE TABLE ENGINE1 (
	ENUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ENAME NVARCHAR(32) UNIQUE NOT NULL
);


CREATE TABLE TRANSMISSION (
	TNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TNAME NVARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE DUNIT (
	DNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DNAME NVARCHAR(32) UNIQUE NOT NULL
);

CREATE TABLE WHEEL (
	WNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	WNAME NVARCHAR(32) UNIQUE NOT NULL
);


CREATE TABLE AD (
	ADNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ADNAME NVARCHAR(100) NOT NULL,
	UNUM INT NOT NULL,
	MNUM INT NOT NULL,
	ADPRICE INT NOT NULL,
	ADDESCRIPTION NVARCHAR(1000) NOT NULL,
	ENUM INT NOT NULL,
	EVAL FLOAT NOT NULL,
	TNUM INT NOT NULL,
	DNUM INT NOT NULL,
	WNUM INT NOT NULL,
	MILVAL INT NOT NULL,
	ADDISPLAY BOOL NOT NULL DEFAULT TRUE,
	ADYEAR INT NOT NULL,
	ADPOWER INT NOT NULL,
	
	

	FOREIGN KEY (UNUM) REFERENCES USERS(UNUM),
	FOREIGN KEY (MNUM) REFERENCES MODEL(MNUM),
	FOREIGN KEY (ENUM) REFERENCES ENGINE1(ENUM),
	FOREIGN KEY (TNUM) REFERENCES TRANSMISSION(TNUM),
	FOREIGN KEY (DNUM) REFERENCES DUNIT(DNUM),
	FOREIGN KEY (WNUM) REFERENCES WHEEL(WNUM)
);


CREATE TABLE IMG (
	INUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IADNUM INT NOT NULL,
	INAME NVARCHAR(100) NOT NULL,

	FOREIGN KEY (IADNUM) REFERENCES AD(ADNUM)
);

CREATE TABLE MESSAGE (
	MNUM INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MADNUM INT NOT NULL,
	MUNUM INT NOT NULL,
	MDATE NVARCHAR(8) NOT NULL,
	MVAL NVARCHAR(500) NOT NULL,

	FOREIGN KEY (MADNUM) REFERENCES AD(ADNUM)
);