use autosell;

INSERT INTO USERS (ULOGIN, UPHONE, UEMAIL, UPASS,UTYPE) 
	VALUES ('Admin', '8-800-555-35-35', 'admin@gmail.com', 'password', 'Admin');

INSERT INTO USERS (ULOGIN, UPHONE, UEMAIL, UPASS,UTYPE) 
	VALUES ('lfd','8-913-666-02-28','lexa77159@gmail.com', '123456','User');



INSERT INTO ENGINE1 (ENAME) 
	VALUES ('Бензин');

INSERT INTO ENGINE1 (ENAME) 
	VALUES ('Дизель');

INSERT INTO ENGINE1 (ENAME) 
	VALUES ('Электро');

INSERT INTO ENGINE1 (ENAME) 
	VALUES ('Гибрид');

INSERT INTO ENGINE1 (ENAME) 
	VALUES ('ГБО');



INSERT INTO TRANSMISSION (TNAME) 
	VALUES ('Автомат');

INSERT INTO TRANSMISSION (TNAME) 
	VALUES ('Механика');




INSERT INTO DUNIT (DNAME) 
	VALUES ('4WD');

INSERT INTO DUNIT (DNAME) 
	VALUES ('Передний');

INSERT INTO DUNIT (DNAME) 
	VALUES ('Задний');



INSERT INTO WHEEL (WNAME) 
	VALUES ('Левый');

INSERT INTO WHEEL (WNAME) 
	VALUES ('Правый');



INSERT INTO BRAND (BNAME) 
	VALUES ('Toyota');

INSERT INTO BRAND (BNAME) 
	VALUES ('Nissan');

INSERT INTO BRAND (BNAME) 
	VALUES ('Mercedes-Benz');

INSERT INTO BRAND (BNAME) 
	VALUES ('Honda');

INSERT INTO BRAND (BNAME) 
	VALUES ('BMW');

INSERT INTO BRAND (BNAME) 
	VALUES ('Hyundai');



INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (1, 'Camry');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (1, 'Corolla');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (1, 'RAV4');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (1, 'Land Cruiser Prado');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (1, 'Land Cruiser');


INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (2, 'X-Trail');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (2, 'Qashqai');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (2, 'Note');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (2, 'Leaf');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (2, 'Sunny');



INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (3, 'E-Class');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (3, 'S-Class');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (3, 'C-Class');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (3, 'M-Class');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (3, 'GLC');



INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (4, 'Fit');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (4, 'CR-V');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (4, 'Accord');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (4, 'Civic');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (4, 'Stepwgn');



INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (5, '5-Series');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (5, '3-Series');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (5, 'X5');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (5, 'X3');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (5, 'X6');


INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (6, 'Solaris');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (6, 'Creta');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (6, 'Santa Fe');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (6, 'Accent');

INSERT INTO MODEL (BNUM, MNAME) 
	VALUES (6, 'ix35');

INSERT INTO AD (ADNAME, UNUM, MNUM, ADPRICE, ADDESCRIPTION, ENUM, EVAL, TNUM, DNUM, WNUM, MILVAL, ADYEAR, ADPOWER) 
	VALUES ('Продажа Honda Accord', 2, 18, 580000, 'Аккорд в хорошем состоянии', 1, 2.4, 2, 2, 1, 267000, 2006, 190);

INSERT INTO AD (ADNAME, UNUM, MNUM, ADPRICE, ADDESCRIPTION, ENUM, EVAL, TNUM, DNUM, WNUM, MILVAL, ADYEAR, ADPOWER) 
	VALUES ('Продажа Toyota Camry, 2018 год в Новосибирске', 2, 1, 2100000 , 'Автомобиль покупался новым у официального дилера', 1, 3.5, 1, 2, 1, 56000, 2018, 249);